server:
    port: 8081

spring:
    application:
        name: buscador
    
    datasource:
        url: jdbc:mysql://monorail.proxy.rlwy.net:27601/buscador
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: KJCgKEczAzTmbVriQjoqukpDnGLWTtgg

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                
springdoc:: 
    swagger-ui: 
        disable-swagger-default-url: true
        path: /myswagger
        